### ISSUE TITLE
You need the PHP extension "yaml" in order to use TopLevelView

### ISSUE THREAD

**Issue by Thatdarkone** [Icinga/icingaweb2-module-toplevelview#21]
I installed the yaml PHP extension and yet im getting this error when going to top level view menu

"You need the PHP extension "yaml" in order to use TopLevelView"

```
#0 /usr/share/php/Icinga/Web/Controller/ActionController.php(139): Icinga\Module\Toplevelview\Web\Controller->init()
#1 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#3 /usr/share/php/Icinga/Application/Web.php(389): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/share/php/Icinga/Application/webrouter.php(109): Icinga\Application\Web->dispatch()
#5 /usr/share/icingaweb2/public/index.php(4): require_once('/usr/share/php/...')
#6 {main}

```

[root@modules]# rpm -qa | grep yaml
libyaml-0.1.4-11.el7_0.x86_64
php-pecl-yaml-1.1.1-5.el7.x86_64

icingaweb2 2.4.1
icinga 2.7.0

Extension installed in 

/usr/share/icingaweb2/modules

Restarted icinga and enable/disable module several times to no avail.

**Comment by nilmerg** [comment]
Hey, did you try to restart your webserver? (presumably httpd) As this is a extension for php and php in turn is probably a module for your webserver.

**Comment by Thatdarkone** [comment]
Something crossed my mind and I just restarted httpd and it worked . Thanks for the tip though.
I suggest the doc to be updated
