### ISSUE TITLE
Apply monitoring filter to views

### ISSUE THREAD

**Issue by dgoetz** [Icinga/icingaweb2-module-toplevelview#25]
If filters are configured for the monitoring module by monitoring/filter/objects hosts are displayed in the toplevelview with their state and clicking them tells "Host not found". The toplevelview should honor those filters somehow, e.g. not showing the host/service and grey out a section with no monitoring object.

**Comment by lazyfrosch** [comment]
That is not a good idea with the query engine behind TLV. Filters are hard enough on the database, and this doesn't scale with this view.

What is possible would be to add permissions limiting listing the TLV views the user can access.

See #26
