### ISSUE TITLE
SQL-Function UTC_DATE() not available under PostgreSQL

### ISSUE THREAD

**Issue by rafaelorafaelo** [Icinga/icingaweb2-module-toplevelview#27]
Hi,
HostgroupQuery.php and ServicestatusQuery.php contain SQL calls with a function UTC_DATE(). This seems to be a MySQL-only function not available under PostgreSQL. Something close to SQL Standards could be CURRENT_DATE according to https://en.wikibooks.org/wiki/SQL_Dialects_Reference/Functions_and_expressions/Date_and_time_functions

Ralf

**Comment by rafaelorafaelo** [comment]
Same for UNIX_TIMESTAMP() - it's only available in MySQL. Under PostgrSQL: use EPOCH according to https://www.postgresql.org/docs/10/static/functions-datetime.html

**Comment by lazyfrosch** [comment]
This module hasn't been tested against PostgreSQL at all...

Does the SQL magic work with the other function names? Can you test and send in an PR?

**Comment by lazyfrosch** [comment]
Supporting PostgreSQL won't happen here anytime soon, so closing this.

Sorry :disappointed:
