### ISSUE TITLE
Tiles are sized to fit the whole screen

### ISSUE THREAD

**Issue by voiprodrigo** [Icinga/icingaweb2-module-toplevelview#31]
Hi,

Giving this module a test-drive. I created a test configuration which has 4 top-level tiles. When clicking in the view link in the menu, I get a screen with the 4 tiles evenly split horizontally, but using 100% height. In one occasion, I was able to see it "normally", with the tiles sized vertically just enough, but I have no idea how to reproduce it, can't get back to that get screen.

Maybe this is by design, or maybe I'm missing something, can you help clarify?

Thanks

**Comment by lazyfrosch** [comment]
Yes TLV is designed to fit a screen at 100% (with many tiles and a few categories).

CSS might not be optimal in any case, but layout is purely CSS using flex.
