### ISSUE TITLE
Feature Request: Add support for pgsql backend

### ISSUE THREAD

**Issue by e1ze** [Icinga/icingaweb2-module-toplevelview#32]
Hi,

our default database backend system is pgsql, so we use it for all icinga related components.
It causes additional effort, but so far pgsql works quite well with all icinga related components.

So it would be nice if support for pgsql could be added.
 
If i create a test view and save the settings i get the following error message about day/time calculation:

```sql
SQLSTATE[42601]: Syntax error: 7 ERROR: syntax error at or near "("
LINE 8: AND ntpr.day = DAYOFWEEK(CURRENT_DATE()) - 1
^, query was: SELECT so.name1 AS host_name, so.name2 AS service_description, CASE WHEN ss.has_been_checked = 0 OR ss.has_been_checked IS NULL THEN 99 ELSE CASE WHEN ss.state_type = 1 THEN ss.current_state ELSE ss.last_hard_state END END AS service_hard_state, CASE WHEN (ss.problem_has_been_acknowledged + ss.scheduled_downtime_depth + COALESCE(hs.current_state, 0)) > 0 THEN 1 ELSE 0 END AS service_handled, CASE WHEN ss.problem_has_been_acknowledged > 0 THEN 1 ELSE 0 END AS service_handled_wo_host, ss.notifications_enabled AS service_notifications_enabled, ntpo.name1 AS service_notification_period, ss.is_flapping AS service_is_flapping, CASE WHEN (ss.scheduled_downtime_depth = 0 OR ss.scheduled_downtime_depth IS NULL) THEN 0 ELSE 1 END AS service_in_downtime FROM icinga_objects AS so
INNER JOIN icinga_services AS s ON s.service_object_id = so.object_id AND so.is_active = 1 AND so.objecttype_id = 2
INNER JOIN icinga_hoststatus AS hs ON hs.host_object_id = s.host_object_id
INNER JOIN icinga_servicestatus AS ss ON ss.service_object_id = so.object_id
LEFT JOIN icinga_timeperiods AS ntp ON ntp.timeperiod_object_id = s.notification_timeperiod_object_id AND ntp.config_type = 1 AND ntp.instance_id = s.instance_id
LEFT JOIN icinga_objects AS ntpo ON ntpo.object_id = s.notification_timeperiod_object_id
LEFT JOIN icinga_timeperiod_timeranges AS ntpr ON ntpr.timeperiod_id = ntp.timeperiod_id
AND ntpr.day = DAYOFWEEK(CURRENT_DATE()) - 1
AND ntpr.start_sec < UNIX_TIMESTAMP() - UNIX_TIMESTAMP(CURRENT_DATE())
AND ntpr.end_sec > UNIX_TIMESTAMP() - UNIX_TIMESTAMP(CURRENT_DATE())
WHERE (so.name1 IN ('test1', 'test2', 'test3', 'test4')) ORDER BY LOWER(s.display_name) ASC
```

Monday: (DAYOFWEEK)
`extract(isodow from current_date) - 1` - [postgresql date/time functions](https://www.postgresql.org/docs/11/functions-datetime.html)

UNIX_TIMESTAMP:
`select extract(epoch from now());` - [postgresql date/time datatype](https://www.postgresql.org/docs/11/datatype-datetime.html)

If you need further feedback or testing, please let me know.

One more side-note: I had to change the **php-pecl-yaml** spec file (`rh-php71-php-pecl-yaml-2.0.2-3.el7.x86_64.rpm` & `rh-php71-php-pecl-yaml-debuginfo-2.0.2-3.el7.x86_64.rpm`) for **rh-php71** on CentOS7 systems to default build against scl rh-php71 -> [php-pecl-yaml.spec](https://gist.github.com/e1ze/a998122d816afdee0e3864c156938f2d)

Thank you

Greetings René

**Comment by e1ze** [comment]
Oh, yes, it is a duplicate. Sorry i missed that one.

**Comment by lazyfrosch** [comment]
Supporting PostgreSQL won't happen here anytime soon, so closing this.

Sorry :disappointed:
