### ISSUE TITLE
You need the PHP extension "yaml" in order to use TopLevelView

### ISSUE THREAD

**Issue by rtritscher** [Icinga/icingaweb2-module-toplevelview#41]
Hi,

I installed the yaml PHP Extension and restarted httpd, but still getting this error when I open toplevelview:

"You need the PHP extension "yaml" in order to use TopLevelView"

```
#0 /usr/share/php/Icinga/Web/Controller/ActionController.php(152): Icinga\Module\Toplevelview\Web\Controller->init()
#1 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(59): Icinga\Web\Controller\ActionController->__construct(Object(Icinga\Web\Request), Object(Icinga\Web\Response), Array)
#2 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#3 /usr/share/php/Icinga/Application/Web.php(300): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#4 /usr/share/php/Icinga/Application/webrouter.php(99): Icinga\Application\Web->dispatch()
#5 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#6 {main}
```

Icinga Web 2.7.3
Icinga 2.10.7-1
toplevelview 0.3.1 
PHP Version 7.1.8

```
# rpm -qa | grep yaml
libyaml-0.1.4-11.el7_0.x86_64
php-pecl-yaml-1.3.0-1.el7.remi.5.4.x86_64
```

Thank you
Robert

**Comment by lazyfrosch** [comment]
Unfortunately pecl-yaml is not available with `rh-php71-*` which is used by Icinga Web 2 on CentOS 7.

I've added a [SPEC file](https://github.com/Icinga/icingaweb2-module-toplevelview/blob/master/contrib/php-pecl-yaml.spec) to the repository.

Can't help with this problem here...

**Comment by nilmerg** [comment]
Icinga Web 2.8+ packages will install PHP 7.3 on CentOS 7. Just [upgrade to this version](https://icinga.com/docs/icingaweb2/latest/doc/80-Upgrading/#upgrading-to-icinga-web-2-28x) and you should be able to install the respective yaml extension.

**Comment by firatalkis** [comment]
hi,

Icinga2  2.10.5-1
Icinga Web 2  2.8.2  
PHP Version   7.3.11
toplevelview  0.3.1

but same error "You need the PHP extension "yaml" in order to use TopLevelView".

rpm -qa | grep yaml

libyaml-0.1.4-11.el7_0.x86_64
php-pecl-yaml-1.1.1-5.el7.x86_64

Could you suggest please what can i do it?
