### ISSUE TITLE
You need the PHP extension "yaml" in order to use TopLevelView (NEW)

### ISSUE THREAD

**Issue by firatalkis** [Icinga/icingaweb2-module-toplevelview#42]
Hi,

Icinga2 2.10.5-1
Icinga Web 2 2.8.2
PHP Version 7.3.11
toplevelview 0.3.1

but same error "You need the PHP extension "yaml" in order to use TopLevelView".

rpm -qa | grep yaml

libyaml-0.1.4-11.el7_0.x86_64
php-pecl-yaml-1.1.1-5.el7.x86_64

Could you suggest please what can i do it?
Thanks.

**Comment by martialblog** [comment]
Hi, 

might be that the YAML extension is not yet enabled in the PHP runtime.

I'd try to verify that with `php -m` and if it is not in the module list, then enable it (depends on how PHP is executed, refer to the PHP/Webserver docs)

I'm closing this issue for now
