### ISSUE TITLE
Add support for icingadb

### ISSUE THREAD

**Issue by sukhwinder33445** [Icinga/icingaweb2-module-toplevelview#46]
Provide icingadb support.

**Comment by lippserd** [comment]
Really? Why? 😆

**Comment by sukhwinder33445** [comment]
This module depends on monitoring. It should also support icingadb, right? i made a list with johannes of modules that should support icingadb, this module was also included.

**Comment by Tontonitch** [comment]
Indeed, no way to test the module after an icingadb migration:
```
The module "monitoring" must be enabled and configured!

#0 /usr/share/icingaweb2/modules/toplevelview/application/controllers/ShowController.php(61): Icinga\Module\Toplevelview\Web\Controller->monitoringBackend()
#1 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action.php(507): Icinga\Module\Toplevelview\Controllers\ShowController->indexAction()
#2 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#3 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#4 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#5 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#6 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#7 {main}
```

Should this module be considered as dying, of is it still on the roadmap of icinga products?

**Comment by martialblog** [comment]
I have started working on this. A preview should be ready soon. 

Not 100% sure yet what the roadmap is. But I'm thinking: on final release with the Monitoring module backend, just to include some polish I've been working on. And then afterwards only Icinga DB Web.
