### ISSUE TITLE
Use the display_name instead of the name of the object in the output of the tree

### ISSUE THREAD

**Issue by gbin2265** [Icinga/icingaweb2-module-toplevelview#55]
Hello, 

Thank you @martialblog for making this module compatible with IcingaDB.
For me, this module also has its value.

Is it possible to use the display name instead of the name (object name) when viewing the tree ?

Name : redhat_linux_127_0_0_2      -> This is what is stated in the YAML file and is currently used in the output
Display Name : server127.dns.com  -> This is the friendly name, to be used in the output if possible.

Perhaps you could provide a parameter in the YAML to make this switch?
Or a global parameter in the config file of the module.

regards,
Geert

**Comment by martialblog** [comment]
Hi, thanks for the feedback. Wasn't sure anyone still uses this module.

Should be possible to use the display name, I'll have a look at it.

Regards,
Markus

**Comment by martialblog** [comment]
@gbin2265 Hi, if you want you can check this branch out: https://github.com/Icinga/icingaweb2-module-toplevelview/pull/57

I think a good solution is to use the display_name if set on an object, as the name implies it is used for displaying. 

Feedback is welcome

**Comment by gbin2265** [comment]
Thank you for the modifications. 

This is much more readable because we use names like host_linux_192_168_001_001 and display names like home.dns.com.

However, could it be that it only works for a HOST or HOSTGROUP,  but not for a HOST in combination with a SERVICE? 
In that case, the object name is still used instead of the display name.

regards,
Geert

**Comment by martialblog** [comment]
Thanks for the feedback! I'll have a look at it.

**Comment by martialblog** [comment]
I fixed it on the `fix/displaynames` branch

**Comment by gbin2265** [comment]
I have tested the modification and it works.
Thank you!

**Comment by martialblog** [comment]
Perfect. This will make it into the next release
